# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Labs\interface2.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(812, 625)
        MainWindow.setStyleSheet("\n"
"background-color: rgb(231, 231, 231);\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.radioLagrange = QtWidgets.QRadioButton(self.centralwidget)
        self.radioLagrange.setGeometry(QtCore.QRect(20, 320, 161, 31))
        self.radioLagrange.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";")
        self.radioLagrange.setObjectName("radioLagrange")
        self.radioAitken = QtWidgets.QRadioButton(self.centralwidget)
        self.radioAitken.setGeometry(QtCore.QRect(20, 360, 161, 31))
        self.radioAitken.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";")
        self.radioAitken.setObjectName("radioAitken")
        self.Save = QtWidgets.QPushButton(self.centralwidget)
        self.Save.setGeometry(QtCore.QRect(20, 520, 210, 50))
        self.Save.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(181, 181, 181);")
        self.Save.setObjectName("Save")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 280, 201, 31))
        self.label.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(280, 19, 150, 20))
        self.label_2.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 20, 220, 20))
        self.label_3.setStyleSheet("font: 8pt \"MS Shell Dlg 2\";\n"
"font: 9pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 90, 55, 16))
        self.label_4.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(280, 449, 150, 20))
        self.label_5.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";")
        self.label_5.setObjectName("label_5")
        self.toCalculate = QtWidgets.QPushButton(self.centralwidget)
        self.toCalculate.setGeometry(QtCore.QRect(20, 450, 210, 50))
        self.toCalculate.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(181, 181, 181);\n"
"")
        self.toCalculate.setObjectName("toCalculate")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(20, 160, 55, 16))
        self.label_6.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";")
        self.label_6.setObjectName("label_6")
        self.inputX = QtWidgets.QLineEdit(self.centralwidget)
        self.inputX.setGeometry(QtCore.QRect(20, 110, 211, 31))
        self.inputX.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);")
        self.inputX.setObjectName("inputX")
        self.inputY = QtWidgets.QLineEdit(self.centralwidget)
        self.inputY.setGeometry(QtCore.QRect(20, 180, 211, 31))
        self.inputY.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);")
        self.inputY.setObjectName("inputY")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(280, 470, 511, 101))
        self.textEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 9pt \"MS Shell Dlg 2\";")
        self.textEdit.setObjectName("textEdit")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(280, 40, 511, 361))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.graf = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.graf.setContentsMargins(0, 0, 0, 0)
        self.graf.setObjectName("graf")
        self.outFile = QtWidgets.QPushButton(self.centralwidget)
        self.outFile.setGeometry(QtCore.QRect(20, 50, 211, 28))
        self.outFile.setObjectName("outFile")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Interpolation Calculator"))
        self.radioLagrange.setText(_translate("MainWindow", "метод Лагранджа"))
        self.radioAitken.setText(_translate("MainWindow", "схема Ейткена"))
        self.Save.setText(_translate("MainWindow", "Зберегти у файл"))
        self.label.setText(_translate("MainWindow", "Оберіть метод розрахунку:"))
        self.label_2.setText(_translate("MainWindow", "Графік поліному:"))
        self.label_3.setText(_translate("MainWindow", "Введіть точки для розрахунку:"))
        self.label_4.setText(_translate("MainWindow", "Х:"))
        self.label_5.setText(_translate("MainWindow", "Знайдений поліном:"))
        self.toCalculate.setText(_translate("MainWindow", "Розрахувати"))
        self.label_6.setText(_translate("MainWindow", "У:"))
        self.outFile.setText(_translate("MainWindow", "Загрузити з файлу"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
